---
- hosts: ansible-server
  #become: true

  tasks:

  - name: building docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/kubernetes

  - name: create tag image
    command: docker tag simple-devops-image rajuhp/simple-devops-image

  - name: push image on doker hub
    command: docker push rajuhp/simple-devops-image


  - name: remove docker image from ansible server
    command: docker rmi simple-devops-image:latest rajuhp/simple-devops-image
    ignore_errors: yes