---
- name: Create pods using deployment
  hosts: k8-management-server
  become: true
  user: root

  tasks:
  - name: create a deployment
    command: kubectl apply -f deployment.yml

  - name: update deployment with new pod, if image update in Docker hub
    command: kubectl rollout restart deployment.apps/k8s-deployment